title: The Amazing World Of Discord
author: Shay Cromwell
email: shaylacromwell17@gmail.com
description: Find out all of discords amazing features.

# social links
instagram_username: _shay.cromwell
github_username:  shaycromwell
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
